### ISSUE TITLE
The wind paths created were not correct and different from the actual wind paths. So I wanted to know how exactly is the wind path computed? Also the U and V are the U and V components of Velocity at a point right? 

### ISSUE THREAD

**Issue by ankit-shibu** [RaymanNg/3D-Wind-Field#11]

**Comment by RaymanNg** [comment]
Can you please post a image to show the difference?

U and V are velocity at specified position, I used Bicubic Interpolation to draw the wind.

**Comment by ankit-shibu** [comment]
![image](https://user-images.githubusercontent.com/42924915/59589530-cd7f9580-9107-11e9-86bc-305ae080c382.png) 

same data in leaflet-velocity
![image](https://user-images.githubusercontent.com/42924915/59589603-f0aa4500-9107-11e9-9dc9-26b7dd8b2226.png)

**Comment by RaymanNg** [comment]
+ Firstly, make sure you really used the same data
+ There are several kinds of lines: Streamlines, streaklines, and pathlines([wiki](https://en.wikipedia.org/wiki/Streamlines,_streaklines,_and_pathlines)) and so on. The lines in my demo is just the wind field itself (none of them)
+ Different algorithms may yields slightly different result when rendering the same kind of line.

Here is a screenshot of Earth NullSchool rendering the same data as my demo.nc
https://earth.nullschool.net/#2018/09/16/0000Z/wind/surface/level/orthographic=-278.10,11.73,1484
![image](https://user-images.githubusercontent.com/18614142/59592668-10029b80-9123-11e9-8216-5ab82ef8dde4.png)

**Comment by ankit-shibu** [comment]
And how is the data stored in demo.nc
u[0],v[0]->lat=-90,lon=0
u[1],v[1]->lat=-89.5,lon=0;
u[2],v[2]->lat=-89,lon=0;
....... so on?

**Comment by RaymanNg** [comment]
Now you can read the updated README file for the data layout
https://github.com/RaymanNg/3D-Wind-Field#data-layout

**Comment by ankit-shibu** [comment]
Thank You! My data had different structure and so the problem.
