### ISSUE TITLE
I have more than one data file to be projected. How can I stop the rendering of one layer and replace it with new data?TIA

### ISSUE THREAD

**Issue by ankit-shibu** [RaymanNg/3D-Wind-Field#13]

**Comment by RaymanNg** [comment]
1. stop rendering (`scene.primitives.show = false;` in wind3D.js)
2. load the new NetCDF data in dataProcess.js
3. destroy the old textures in particlesComputing.js
4. create the new textures in particlesComputing.js using new data
5. resume the rendering (`scene.primitives.show = true;` in wind3D.js)

**Comment by ankit-shibu** [comment]
![Capture](https://user-images.githubusercontent.com/42924915/59961627-df8e7900-94f7-11e9-974a-a818f3af389d.PNG)
I tried this. and on changing the data file the new data was rendered while the old particles remained. Also I got these errors:
![Capture1](https://user-images.githubusercontent.com/42924915/59961660-59266700-94f8-11e9-9546-347eb46d853a.PNG)
Pls could you tell me what am I doing wrong?

**Comment by sunday60004** [comment]
Hello, I can actually switch to the new data, but the FPS value will double, the wind speed will become faster, can you guide me how to solve this problem?
![image](https://user-images.githubusercontent.com/28419917/60005593-6599f380-96a1-11e9-9e1b-e2de34a6c790.png)
![image](https://user-images.githubusercontent.com/28419917/60005638-78142d00-96a1-11e9-9033-351d185200a8.png)

**Comment by sunday60004** [comment]
> Hello, I can actually switch to the new data, but the FPS value will double, the wind speed will become faster, can you guide me how to solve this problem?
> ![image](https://user-images.githubusercontent.com/28419917/60005593-6599f380-96a1-11e9-9e1b-e2de34a6c790.png)
> ![image](https://user-images.githubusercontent.com/28419917/60005638-78142d00-96a1-11e9-9033-351d185200a8.png)

When loading new data and executing loadData again, don't execute ”this.debug()“, this looks like it’s working, can it be?

**Comment by RaymanNg** [comment]
@godswo123 
Did you create the new textures after destroying the old ones? If so, how did you create those textures?

You also need to refresh the particles after creating the new textures, there is a refresh method in particleSystem.js

**Comment by RaymanNg** [comment]
@sunday60004 

Please follow the order I provided, you should load the new data before manipulating textures

use the refreshParticles method in particleSystem.js, it will call the destroy method and reset the paticles for you

**Comment by ankit-shibu** [comment]
Thanks
