### ISSUE TITLE
Where is the color controlled?

### ISSUE THREAD

**Issue by sunday60004** [RaymanNg/3D-Wind-Field#14]
I know that a color interval can be defined in the colorTable file, but what is the specific color corresponding to what value is judged?

**Comment by RaymanNg** [comment]
This demo uses the color table "GMT_panoply" in [NCL Graphics](https://www.ncl.ucar.edu/Document/Graphics/color_table_gallery.shtml)

**Comment by sunday60004** [comment]
Thanks
