### ISSUE TITLE
I have data of wind at different heights and I want to display the particles at different heights? 

### ISSUE THREAD

**Issue by ankit-shibu** [RaymanNg/3D-Wind-Field#15]

**Comment by ankit-shibu** [comment]
I want to render multiple data at the same time. I am creating an array of particleSystems in Wind3D.js and without deleting the previous textures. It renders fine but on zooming or mousemove the previous layer loses its positions. Please help.

**Comment by RaymanNg** [comment]
This demo should support multiple layers at different height (corresponding to the lev dimension), but you need to combine all the data in a single NetCDF file.

If you need to render multiple data dynamically, delete all the old textures, flatten all the new wind data into a single 1D array, create the textures and resume your rendering
