### ISSUE TITLE
There may be something wrong with the NC data in demo

### ISSUE THREAD

**Issue by oubaguilai** [RaymanNg/3D-Wind-Field#16]
Dear author ，When I magnified the map, I found that the wind field had obvious boundaries，I put in the latest data, and the wind show is smoother.but I still have a few questions.
1.As the map zooming in, the number of particles increases, can it be kept constant? 
2.particles's pixel width is not a fixed pixel,when the map zooming in, the width will slowly increase.

**Comment by RaymanNg** [comment]
1. The number of particles will not change unless you modify the parameter, but I limit all the particles in the visible area(i.e., the area camera can see) so that the computation of particles will not be wasted.

2. I think it is a bit difficult to keep the particle pixel size fixed, because it gets involved with geometry computation which is sort of complicate. For now I just simply modify the pixel size according to the distance from particle to camera

**Comment by oubaguilai** [comment]
Thank you for your answer，now I  know why about question 1，and I am sure that the number of particles is not change, The illusion is only because fadeOpacity and speedFactor  not appropriate on a small scale。
but now I want to express the size in terms of speed,not colors,Do you have any suggestions? thank you!
![1](https://user-images.githubusercontent.com/24708305/60429826-824ca300-9c2e-11e9-935f-4410772f8851.png)
![2](https://user-images.githubusercontent.com/24708305/60429845-8973b100-9c2e-11e9-930f-5a8ef61d7ba3.png)

**Comment by oubaguilai** [comment]
and I didn't get it about how Cesium.PrimitiveType.TRIANGLES can Draw point or line

**Comment by RaymanNg** [comment]
Do you have knowledge of WebGL ( or OpenGL)?
If not, I suggest you learn the basis before you start coding.

And for your question, two triangle can make a rectangle, and a line is just a group of long thin rectangle combined together. The knowledge about Computer Graphics and OpenGL can help you understand the rendering code more easily.

Modify a unfamiliar program is painful, so my suggestion is to understand it at first. For what you want, you can change the size dynamically by changing the GLSL code

**Comment by oubaguilai** [comment]
I just started learning webgl for a short time，and I will accept your advice sincerely,Thank you very much!
