### ISSUE TITLE
I am having an issue with creating the http server? Could someone share the code or help me out here

### ISSUE THREAD

**Issue by ankit-shibu** [RaymanNg/3D-Wind-Field#17]
![Capture](https://user-images.githubusercontent.com/42924915/60799633-22577e80-a191-11e9-97f2-31dfcb72d413.PNG)
my code
![Capture](https://user-images.githubusercontent.com/42924915/60799748-6480c000-a191-11e9-8231-eb2acba98313.PNG)
error

**Comment by RaymanNg** [comment]
I can not figure out what is the problem, you probably need to check the generated js file.

Also it may help if you seek for help in the forum of the HTTP server you use
