### ISSUE TITLE
mobile devices don't support WebGL Extension EXT_frag_depth

### ISSUE THREAD

**Issue by yvonne20061** [RaymanNg/3D-Wind-Field#19]
My phone (IPHONE XR) does not support WebGL Extension EXT_frag_depth :(
I tested it on the android device, it is also not support.
Is there any way to fix it?
![File (2)](https://user-images.githubusercontent.com/54659675/63915863-a7f8fb80-ca69-11e9-95b8-35174bfeda06.jpg)

**Comment by RaymanNg** [comment]
Unfortunately, it seems that there are many mobile phones that do not support WebGL Extension EXT_frag_depth.

And, I don't think there is a easy way to work around. Check this [SO post](https://stackoverflow.com/questions/24101017/webgl-alternative-to-writing-to-gl-fragdepth) for more info.

If you really want to do that, I think at least you need to modify the GLSL code (especially trailDraw.frag)
1. get the depth texture of points, trails and globe
2. compare the depth value and store the correct frag color and depth in textures
3. use the stored result to manipulate gl_Position.z and render the result

It is not a simple modification, I hope you can find a easier solution

**Comment by yvonne20061** [comment]
Thank you so much for your reply and advice.

**Comment by zouyaoji** [comment]
@yvonne20061 Hello, did you solve this problem?
