### ISSUE TITLE
How to display particules only in one geaographic zone

### ISSUE THREAD

**Issue by KavamiDev** [RaymanNg/3D-Wind-Field#20]
I have a netcdf Files , contain data in one geopgraphic zone , but the particules display in all the earth , how to centralize ? 

(don't pay attention about my english , because i'm not good)

**Comment by RaymanNg** [comment]
Currently the particles display range is the same as wind data range.
May I ask you why do you want to display the particles outside the wind field ?

One solution I come up with is modifying the source code so that the particles keep going even if it is outside the wind field, but I am not sure if it will give the result you want.

**Comment by KavamiDev** [comment]
Hum , thnaks for your answer , 
I need to display particles in one geographique zone . My data files is for example "lon -40 90 lat 40 1 " is not a files on all earth , BUT particles is all the earth. 

I think i need to have global parameter like 

		range.lat = {
			min: -40,
			max: -1
		}
But  i need to change this value when the netcdf file change de range 
I think i have to look at 

data.lon = {};
                data.lon.array = new Float32Array(NetCDF.getDataVariable('lon').flat());
                data.lon.min = Math.min(...data.lon.array);
                data.lon.max = Math.max(...data.lon.array);

I need to have data.lon.min and max  as global variable

**Comment by KavamiDev** [comment]
It's okay , i found a solution   . 

You need to do this . and take a good parameter in the function 'addviewerparameter'
this.viewerParameters.lonRange.x = data.lon.min;

and now , you can have the wind just in one geographic zone. (If you didn't need all the earth but just pay attention in this zone.

**Comment by KavamiDev** [comment]
I would like to make sure that the wind does not continue outside the geographical limits

Do you have any idea ? 

sry to make a long discution about that but , i need :/ 
![wind_visual](https://user-images.githubusercontent.com/51117467/66305973-97159280-e911-11e9-9e5a-2fea7eb6f265.png)
