### ISSUE TITLE
Do you know how to drag the Panel control ? 

### ISSUE THREAD

**Issue by KavamiDev** [RaymanNg/3D-Wind-Field#21]
I want to drag the panel control , because i have 2 (or more) file netcdf .

**Comment by RaymanNg** [comment]
It is easy to modify the GUI, basically you just modify the gui.js. 
This repo uses [dat.gui](https://github.com/dataarts/dat.gui) library, you may need to read the document

**Comment by KavamiDev** [comment]
Thanks
