### ISSUE TITLE
What tools are available to debug shader code?

### ISSUE THREAD

**Issue by AlbertEjiestein** [RaymanNg/3D-Wind-Field#25]
What tools do you usually use to debug shader code?I'm having trouble with this. Could you give me some advice?thank you very much!

**Comment by RaymanNg** [comment]
Unfortunately, there is no easy way to debug WebGL code, and I can't find any debugging tool for setting breakpoints in WebGL.

For the moment, I rely on [Spector.js](https://github.com/BabylonJS/Spector.js) to figure out what is happening with my WebGL code.  It can tell you the input and output of your code

**Comment by AlbertEjiestein** [comment]
Thanks for you help, I will try your debugging method.
