### ISSUE TITLE
About NetCDF data

### ISSUE THREAD

**Issue by AlbertEjiestein** [RaymanNg/3D-Wind-Field#26]
(1)In the data you provided, the lev of the dimensions variable is 1, now I have a data, lev is 30, but when I run it, it throws an error: the height should be less than or equal to the maximum texture size (8192). I tried to change the maximum texture size and unfortunately failed. So how do I modify the program? Should I change the shader code ?
(2)about the dimension variable, the lon,lat,lev. what does lev means? it means height or else ? 
I need your help and look forward to your answer! thanks very much!

**Comment by RaymanNg** [comment]
'lev' is level, it means how many levels you have for your (lon, lat) data, a level is just like a layer.

maximum texture size is determined by the hardware, and I don't think you can change it.

The error you gave complains that your data is too much to be fit in a texture, the texture size need to be larger than lon * lat * lev, you may consider use a data with less lev instead
