### ISSUE TITLE
About downloading wind data from GFS, how can i filter useless data?

### ISSUE THREAD

**Issue by AlbertEjiestein** [RaymanNg/3D-Wind-Field#27]
Hello, Thank you for helping me out all the time, I'm asking questions again. I tried to download data from your website (GFS), I downloaded 0.5 precision data, the file named "gfsanl_3_20191112_0000_grb2". After the download, I used the ToolsUI.jar which converted to NetCDF format, but there is a problem, I found that the converted .nc file , variables are 147, and you provide wind data in only 8 variables. If I only want wind field data, how can I filter out useless data from my .nc data ? Are you using any Tools, or does tools.jar come with its own filter?

**Comment by RaymanNg** [comment]
As said by README, you can use NCO (NetCDF Operator) or CDO (Climate Data Operator) to process the NetCDF data. Both of them provides a complete document.

I use NCO for this demo, you can check the [Util](https://github.com/RaymanNg/3D-Wind-Field/tree/master/Util) directory for how I use NCO.

**Comment by AlbertEjiestein** [comment]
ok，thanks for you help, i will try your method.
