### ISSUE TITLE
I found that the particles would stop after running for a period of time

### ISSUE THREAD

**Issue by callmeYe** [RaymanNg/3D-Wind-Field#28]
I ported the code to react, and the version of cesium used was 1.60, and I found that the particles would stop after running for a period of time. What might be the reason for this?

**Comment by callmeYe** [comment]
Another strange phenomenon is that when I change the different basemaps, the length of time the particle system can run is different. When I use the WMS basemap, the particle system is able to run for a long time. When using the NaturalEarthII basemap, the particle system quickly fails to function properly, and the particle system cannot restart rendering when the sphere is moved.

**Comment by RaymanNg** [comment]
This demo use Cesium 1.57 while you are using Cesium 1.60.
Could you try to switch to Cesium 1.57 ?
I suspect that the rendering code was modified in Cesium 1.60.

**Comment by callmeYe** [comment]
It still doesn't work; Here is my code: https://github.com/callmeYe/React-Cesium-WindField
Thanks for your help!

**Comment by RaymanNg** [comment]
Could you please provide some error info ?

In Chrome, you can press F12 to toggle the DevTools and then refresh the web page to see what happen.

**Comment by callmeYe** [comment]
What confuses me is that there is no error message

**Comment by callmeYe** [comment]
![Snipaste_2019-12-26_19-52-31](https://user-images.githubusercontent.com/15107776/71475025-5f83fb80-2819-11ea-8ce9-6e44788caddb.png)

**Comment by RaymanNg** [comment]
It is weird...

Though I don't have a suitable device to run your code, by checking your code, I think the particle refresh method is somehow not working, could you set a breakpoint [here](https://github.com/callmeYe/React-Cesium-WindField/blob/3f1ebb457b42c7097f690be3f48adc5f3224fd28/src/components/TDMap/Olc.Cesium.js#L173) to see whether the event is processed correctly

**Comment by callmeYe** [comment]
When I move the sphere，the event is processed correctly and the particle system will restart rendering. But it still stops after running for a while (when I use  NaturalEarthII as basemap, the particle system will not restart rendering). All listeners works fine.

**Comment by callmeYe** [comment]
All listeners works fine.

**Comment by RaymanNg** [comment]
Did you place the Cesium Asset correctly ?
Please check the URL parameter [here](https://github.com/callmeYe/React-Cesium-WindField/blob/3f1ebb457b42c7097f690be3f48adc5f3224fd28/src/components/TDMap/Olc.Cesium.js#L139).

'Assets/Textures/NaturalEarthII' is a path where Cesium fetches its resource, maybe you should modify that parameter

**Comment by callmeYe** [comment]
Looks like it's loaded correctly:
![Snipaste_2019-12-26_20-53-03](https://user-images.githubusercontent.com/15107776/71476796-e0df8c00-2821-11ea-8c17-4520ad008979.png)
![Snipaste_2019-12-26_20-53-21](https://user-images.githubusercontent.com/15107776/71476808-e5a44000-2821-11ea-96cc-bdc317ca7be3.png)

**Comment by RaymanNg** [comment]
okay, do you still have problems with NaturalEarthII ?

If so, what is the error you got ?

**Comment by callmeYe** [comment]
Yes, I still have problems with all basemap, Including my own basemap service; Please ignore those errors, they are caused by other code in the project:
![Snipaste_2019-12-26_21-06-34](https://user-images.githubusercontent.com/15107776/71477186-9eb74a00-2823-11ea-9d58-f74b8d088fad.png)

**Comment by RaymanNg** [comment]
Maybe we should check WebGL Program...

Could you please 
1. provide a small GIF that illustrating the problem you got
2. use [Spector.js](https://github.com/BabylonJS/Spector.js) to check the WebGL program

**Comment by callmeYe** [comment]
Sorry，I don't konw how to debug WebGL program, and the gif is too big to upload.

**Comment by callmeYe** [comment]
Maybe I can send the gif file to your email?

**Comment by RaymanNg** [comment]
Well, personally, I think basic WebGL skill is necessary if you want to make your own wind map.

Feel free to get back here to discuss when you make some progress

**Comment by RaymanNg** [comment]
> Maybe I can send the gif file to your email?

OK

**Comment by callmeYe** [comment]
I have just sent a email, thanks for your time.

**Comment by callmeYe** [comment]
I got this error:
host outlook-com.olc.protection.outlook.com[104.47.46.33] said: 552 Data size must not exceed 48128K bytes. (in reply to EHLO command)

**Comment by RaymanNg** [comment]
well, there are some websites offering GIF compress function, you may want to have a try

- https://www.iloveimg.com/compress-image/compress-gif
- https://ezgif.com/optimize
- https://gifcompressor.com/

**Comment by callmeYe** [comment]
Sorry for late reply. I have just upload the gif file to my project: https://github.com/callmeYe/React-Cesium-WindField/blob/master/problem.gif

**Comment by RaymanNg** [comment]
Could you try to modify the maxParticles in the panel after the particles stop moving, , and see what happen ?

**Comment by callmeYe** [comment]
https://github.com/callmeYe/React-Cesium-WindField/blob/master/adjust_particles.gif

**Comment by RaymanNg** [comment]
According to your GIF, it seems that the particles random reset is somehow not working, I will look into it when I get some spare time

**Comment by RaymanNg** [comment]
After a quick debug, I think the problem is caused by wrong depth textures in the WebGL program. 

I think you may somehow break the depth texture code when writing the React code

Don't have enough time to investigate further... you can install spectorjs extension in Chrome to debug the WebGL program

**Comment by callmeYe** [comment]
I tried using the spectorjs extension, but I still don't know how to catch the rendering errors after going through the tutorial(http://www.realtimerendering.com/blog/debugging-webgl-with-spectorjs/).

**Comment by callmeYe** [comment]
I found the problem. When the viewer is initialized, requestRenderMode should be set to false. But I still don't understand why. Cesium blog(https://cesium.com/blog/2018/01/24/cesium-scene-rendering-performance/) says that enabling request render Mode to reduce the overall amount of time Cesium renders a new frame and to decrease Cesium’s overall CPU usage in a application and by default, when requestRenderMode is enabled, when the simulation time changes more than 0.0 seconds, a new frame will be requested.

**Comment by RaymanNg** [comment]
Good to see you solve your problem.

I think you probably need to set 'maximumRenderTimeChange' parameter when 'requestRenderMode' is enable. 

However, according to my experience,  requestRenderMode improve the performance in the cost of hurting the user experience, so I usually don't use it.

**Comment by callmeYe** [comment]
I tried to set the maximumRenderTimeChange to Infinity as stated in the blog, and I still get the problems I encountered at the beginning. Thanks again for your patience in these days

**Comment by RaymanNg** [comment]
You may misunderstood the 'maximumRenderTimeChange' parameter

Set it to infinity means that you want to render the scene by manually calling the render function, if you set it to 1.0, the scene will be rendered once per second.

PS: the render cost is mainly on the GPU, since I use WebGL to render. requestRenderMode may be unnecessary because it just decreases the CPU usage.

**Comment by callmeYe** [comment]
Now I understand what these two parameters are used for and why requestRenderMode should not be set to true in this application. (I tried adjusting the value of maximumRenderTimeChange and still no effect)

**Comment by RaymanNg** [comment]
I think the cause is that the clock in the Cesium did not start, it seems that the clock is stopped by default. 

If you check the demo on the Cesium official site, you will find the clock in the bottom of the page is paused.
