### ISSUE TITLE
There is an error, the project can't run.

### ISSUE THREAD

**Issue by Watermelon-S** [RaymanNg/3D-Wind-Field#3]
Hello. I recently learned about cesium, I found your blog post, it feels great, I plan to learn, but I found that github Dome is reporting an error. Locally I use node.js to be the same error. Because I am Novice, I am also trying to read the information, but I can't solve this problem. I hope the author can see that this problem can be fixed, thank you.

message：**"When options.pixelFormat is DEPTH_COMPONENT or DEPTH_STENCIL, this WebGL implementation must support WEBGL_depth_texture.  Check context.depthTexture."**
![image](https://user-images.githubusercontent.com/22389360/57275156-33700a80-70d0-11e9-9679-028559fec186.png)

**Comment by RaymanNg** [comment]
It seems that your device does not support [WEBGL_depth_texture extension](https://www.khronos.org/registry/webgl/extensions/WEBGL_depth_texture/).

You may want to check your WebGL implementation in [WebGL report](https://webglreport.com/), you can find more info in the "Supported Extensions" .

~Also this demo currently can only run in Chrome browser, I will update the README file later.~

**Comment by jsbrujy** [comment]
hello

FYI, this is running well on Firefox
