### ISSUE TITLE
layertoShow  no Effect

### ISSUE THREAD

**Issue by ccmostmosthandsome** [RaymanNg/3D-Wind-Field#30]
select layerToShow noEffect
demo cant show wind

**Comment by RaymanNg** [comment]
I just found that NOAA change its WMS server, and I fixed the URL to load the WMS layer. 
Thanks for your feedback.

As for the wind, it works on Chrome on my PC. Please check:
1. your device, this demo may not work on mobile phone.
2. your network, there may be a timeout if your connection to GitHub is slow

**Comment by AlbertEjiestein** [comment]
Now, the layerToShow is invalid again，is the WMS server changed again?

**Comment by RaymanNg** [comment]
Yes, and the new URL is
https://www.ncei.noaa.gov/thredds/wms/model-gfs-g4-anl-files/201809/20180916/gfsanl_4_20180916_0000_000.grb2

Will update README for how to solve this problem soon

**Comment by qing666888** [comment]
Now, the layerToShow is invalid again，is the WMS server changed again?
