### ISSUE TITLE
How can I exclude specific values ​​from the field?

### ISSUE THREAD

**Issue by berrzebb** [RaymanNg/3D-Wind-Field#31]
If the uv vector value is ignore value, I want don't display it.

I think it's getWind.frag where we look up the u, v vector values, right?
sorry bad english..

my dataset
[DataSet.txt](https://github.com/RaymanNg/3D-Wind-Field/files/4323367/DataSet.txt)
exclude area rectangle
![exclude_area](https://user-images.githubusercontent.com/1243875/76507231-c6679700-648f-11ea-88ef-aa6ff06b3fbc.png)

**Comment by RaymanNg** [comment]
> I think it's getWind.frag where we look up the u, v vector values, right?

Yes

If you want to exclude specific area, you can refer to [this issue](https://github.com/RaymanNg/3D-Wind-Field/issues/1#issuecomment-487003075)

If you want to hide the particles with special uv values, you can simply add an `if` statement in  "postProcessingSpeed.frag".

**Comment by berrzebb** [comment]
Is it possible to get the uvVector value from postProcessingSpeed.frag?
Is particleSpeed's x, y a uv vector value?

I want to exclude the case where the value of uv vector is 0.

So uniform float ignoreValue; add "postProcessingSpeed.Frag"
 and particle.Speed.x and y value equals ignoreValue Check
 but I did not see the effect. Is this the way I tried it?

my modified glsl here
[glsl.txt](https://github.com/RaymanNg/3D-Wind-Field/files/4325359/glsl.txt)
glsl fix list here
1. getUVFrag vec2 mapPositionToNormalizedIndex2D(vec3 lonLatLev) function indexing fix(rounding .5)
2. postProcessingPositionFrag particle bounding dependency data range
3. postProcessingSpeedFrag ignoreValue(default value: 0) condition added but not working
4. updatePositionFrag check speed variable equals ignore value but failed
5. updateSpeedFrag calcRelativeSpeed checking ignore value but failed

my dataset uv vector calculate formula use

Spd = Math.sqrt(U ** 2 + V ** 2)  
Dir = (180 / Math. PI) * Math.atan2(V, U)
U = Math.abs(Spd) * Math.sin((Math.PI / 180) * Dir)
V = Math.abs(Spd) * Math.cos((Math.PI / 180) * Dir)

**Comment by RaymanNg** [comment]
> Is it possible to get the uvVector value from postProcessingSpeed.frag?
> Is particleSpeed's x, y a uv vector value?

Yes, and Yes.

For your problem, I forgot that the calculation and rendering are separate, sorry...

Besides of "postProcessingSpeed.Frag", you also need to modify "segmentDraw.vert" and "segmentDraw.frag".

The postProcessingSpeed will be passed to the segmentDraw for rendering, so you should add a check in segmentDraw.vert/frag, and set the alpha value of RGBA to zero so that the unwanted particles are invisible.

**Comment by berrzebb** [comment]
Thank you. I have another question to ask, can I answer it?
The direction currently being displayed is different from the direction I want. How can I do this?

Can I get directions from glsl?

**Comment by RaymanNg** [comment]
There is no direction in the GLSL code, but you can calculate it since `direction = nextPosition - currentPosition`

**Comment by berrzebb** [comment]
It was corrected as suggested, but the problem was not resolved.
It seems that the speed value is normalized from 0 to 1. But my dataset also contains minus values. What should I do in this case?


In the segmentDraw.vert, assuming that u and v values ​​are normal values, the following code is added.

>     vec4 particleSpeed ​​= texture2D (postProcessingSpeed, particleIndex);
>     float rSpeed ​​= sqrt ((particleSpeed.x * particleSpeed.x) + (particleSpeed.y * particleSpeed.y));
>     if (rSpeed! = ignoreValue) {
>         speedNormalization = particleSpeed.a;
>     } else {
>         speedNormalization = 0.0;
>     }


If the calculated speed value is 0, is the next position value the same?

**Comment by RaymanNg** [comment]
> It seems that the speed value is normalized from 0 to 1. But my dataset also contains minus values. What should I do in this case?

It is okay, because the normalized value of x is calculated by (x - min) / (max - min).

> If the calculated speed value is 0, is the next position value the same?

I am afraid not, since the calculation and rendering are separate, hiding particle does not means that it will not move. If you don't want particles to move, change the code in "updatePosition.frag"

**Comment by berrzebb** [comment]
>  updateSpeed.Frag => calcRelativeSpeed seen
>     float minRelativeSpeed ​​= -speedFactor * pixelSize;
>     float maxRelativeSpeed ​​= speedFactor * pixelSize;

I found that it is normalized with. If this is the case, should ignoreValue be used for mix normalization as well?

**Comment by RaymanNg** [comment]
It depends on what you want to do.
If you want to control the particles position, modify "updatePosition.frag"
If you want to control the particles speed and their color(color is used to represent the speed),  modify "updateSpeed.frag"
If you want to control the rendering of particles, check those "xxxDraw" files.
