### ISSUE TITLE
Question about making effect representing wave

### ISSUE THREAD

**Issue by JinghengHuang** [RaymanNg/3D-Wind-Field#33]
Hello and thank you for this project, I've been trying to intergrate your code into my project which can also represent naval data like wave or current. For now I set the `lineWidth` parameter wider and make it change based on frame number, so it would expand along the way until it disappears, but I also want it to show like a circular shape, like in https://www.ventusky.com/?p=-56.02;54.71;6&l=wave&w=0SJdjA9AA ,instead of a straight line. How exactly can I do that? I'm fairly new to GLSL programming, I think I should make the edge move slower than the center, but how can I do that?

**Comment by RaymanNg** [comment]
well, I don't have experience on rendering such shape, but after some googling I think maybe [GL_TRIANGLE_FAN](https://stackoverflow.com/questions/8043923/gl-triangle-fan-explanation) can help you render the circular shape you want?

**Comment by JinghengHuang** [comment]
Thank you, I'll give it a try
