### ISSUE TITLE
Entity API Approach

### ISSUE THREAD

**Issue by blazetopher** [RaymanNg/3D-Wind-Field#34]
I noticed in your post on the Cesium blog that you mentioned trying the Entity API before shifting to the WebGL/custom primitive approach.  I'm curious if you would be willing to share the Entity API approach that you tried?  

Additionally, apart from performance with high numbers of particles, did you encounter any other issues with the Entity API Approach?

Thanks in advance!

**Comment by RaymanNg** [comment]
Oh, I forgot some detail.

What I remember is that I use the entity [PathGraphics](https://cesium.com/docs/cesiumjs-ref-doc/PathGraphics.html) to draw a moving line. You can either create PathGraphics objects directly or generate a [CZML](https://github.com/AnalyticalGraphicsInc/czml-writer/wiki/CZML-Guide) file which contains all the entity data and load it into Cesium.

> Additionally, apart from performance with high numbers of particles, did you encounter any other issues with the Entity API Approach?

Apart from performance, I am satisfied with Entity API since it is easier to understand and use

**Comment by blazetopher** [comment]
Ok, thank you for the information.  I was heading down the same path with the entity PathGraphics, similar to the [sandcastle Interpolation demo](https://sandcastle.cesium.com/?src=Interpolation.html).

One issue I'm running into is that I don't seem to be able to decouple the animation of the entity/path from the "main" Cesium clock.  So if the scene is "paused", the paths don't continue to animate.

The [CustomDataSource](https://cesium.com/docs/cesiumjs-ref-doc/CustomDataSource.html) allows provisioning of a clock, but I'm not having much luck getting it to work.

Do you have any experience with this aspect of things?  I'm planning on posting to the Cesium Forum as well, but figured I'd ask you too!

**Comment by blazetopher** [comment]
Prior to posting, I searched the forum and came across [this post](https://community.cesium.com/t/how-do-i-loop-a-sampledproperty-instance-infinitely-without-changing-the-viewer-clock/8548)

I think this is the solution I'm looking for, but if you have any additional thoughts, I'm definitely interested!

By the way - I never mentioned it ☝️, but my reason for pursuing the Entity API approach is that we have a requirement for the application to work on mobile devices.  In reading some of the closed issues it sounds like modifying the demo to work on mobile (i.e. removing the EXT_frag_depth extension) is a complicated change.  Is that still the case?

**Comment by RaymanNg** [comment]
> In reading some of the closed issues it sounds like modifying the demo to work on mobile (i.e. removing the EXT_frag_depth extension) is a complicated change. Is that still the case?

yes, and it seems that it will take a long time for most mobile devices to have a complete WebGL2 support
