### ISSUE TITLE
use  that.scene.primitives.show to change show or hide is not prefect

### ISSUE THREAD

**Issue by 2015lalala** [RaymanNg/3D-Wind-Field#35]
you can just hide or show primitives which you added,like that:
for (const item of this.scene.primitives._primitives) {
    if (item.commandType === 'Compute' || item.commandType === 'Draw') {
        item.show = true
    }
}

**Comment by RaymanNg** [comment]
For the moment, hide or show all the primitives is all what I need, so I am okay with setting `scene.primitives.show`.

However, your suggestion will help if someone ask a question for how to hide or show a specified primitive.

**Comment by 2015lalala** [comment]
Thank you for your reply，and i have another question, these service can not access like "Temperature_surface" or “Wind_speed_gust_surface”,Has their service address changed？ Can you help me

**Comment by RaymanNg** [comment]
Sorry for the late reply.

The URL did not change, you may want to check your network.

P.S. If the URL change, you may refer to the README for how to set a new URL
