### ISSUE TITLE
netCDF数据如何进一步处理呢

### ISSUE THREAD

**Issue by lewhonly** [RaymanNg/3D-Wind-Field#36]
我已经使用toolsUI-4.6.15.jar将grib2数据转换成了netCDF，但是这个数据跟作者提供的数据差别挺大的，如何做进一步处理呢，我知道Util文件中种有四个文件，包括processNetCDF.ps1文件，但是如何使用呢

**Comment by lewhonly** [comment]
![netCDF_1](https://user-images.githubusercontent.com/15715364/87295293-8f85b880-c537-11ea-8c84-7740af203842.jpg)
上图，如图所示

**Comment by RaymanNg** [comment]
Hi, I just updated the PowerShell script, set the variables(read the comment in the script) and you are good to go

Note: You need to install NetCDF Operators before running this script

**Comment by lewhonly** [comment]
请问该如何安装 NetCDF Operators 呢，我找了半天也没找到我想要的
https://github.com/nco/nco 是这个地址吗，那么该如何安装呢

**Comment by RaymanNg** [comment]
NCO has an official site on SourceForge: http://nco.sourceforge.net/#Executables
There are installers for variant OS

**Comment by lewhonly** [comment]
Thanks a million!
