### ISSUE TITLE
Wind speed meaning in different data 

### ISSUE THREAD

**Issue by Amber-372** [RaymanNg/3D-Wind-Field#38]
Hi, dear author, another question.
I fount that the wind speed in your project is normalized by min&max of uv in one data.
And when I have two different data that min&max of uv is different far away.  like one's uv is smaller total, the another's uv is bigger total. then I can't tell which position has a bigger wind in your project when I compare them at the same time.
![image](https://user-images.githubusercontent.com/13759303/89604724-71914680-d89e-11ea-9dd1-6689150c5c93.png)
![image](https://user-images.githubusercontent.com/13759303/89604775-8d94e800-d89e-11ea-9fad-3b36e8592afb.png)
If I want have the same meaning of wind speed in project by many different data, what should I do？

**Comment by RaymanNg** [comment]
Probably you can merge these data into a single NetCDF file?  In this way all data is normalized with same min/max.

**Comment by Amber-372** [comment]
> Probably you can merge these data into a single NetCDF file? In this way all data is normalized with same min/max.

I think I need a more free way. because the data is random. Maybe I will define same min/max follow common sense, and use this min/max in all data.
