### ISSUE TITLE
NetCDF data

### ISSUE THREAD

**Issue by Rookiemin** [RaymanNg/3D-Wind-Field#42]
Hi，dear.
My data and effects are as follows.
 Is the cause of this problem with my data?
![1601343086(1)](https://user-images.githubusercontent.com/68091040/94507954-77265f80-0243-11eb-92eb-d220039eff8a.png)
![1601348443(1)](https://user-images.githubusercontent.com/68091040/94507964-80afc780-0243-11eb-8379-b26f8190a965.png)

**Comment by RaymanNg** [comment]
How do you construct your NetCDF file?

Please note that:
- The order of dimensions(lev lat lon) matter, you should have U (lev, lat, lon) and V (lev, lat, lon)
- The range of longitude is [0,360], not [-180, 180]

~~And the size of your data is big, I am not sure your GPU can support a texture which contains 720 * 1440 elements.~~
Forget it, most computers should be able to create a texture with size 4096*4096

**Comment by Rookiemin** [comment]
I'm very sorry, my problem is solved.I have found the reason for this situation, it is an error occurred in the UV attribute reading of  data. Thank you for your generous help.
