### ISSUE TITLE
can't run the demo with url https://raymanng.github.io/3D-Wind-Field/demo/

### ISSUE THREAD

**Issue by woshisuperman** [RaymanNg/3D-Wind-Field#53]
![1607955991(1)](https://user-images.githubusercontent.com/31503506/102093822-92753400-3e5c-11eb-9d50-afb4334bd339.jpg)
seems like something went wrong with the token, but I can't find the place in the code where describes the token, can anybody help, thx

**Comment by RaymanNg** [comment]
Cesium requires access token of [Cesium ION](https://cesium.com/ion/signin/) to access the WorldTerrain data, and I have removed my expired token in the code, you can register an account to acquire a valid token, and use it according to the [document](https://cesium.com/docs/cesiumjs-ref-doc/Ion.html).

**Comment by woshisuperman** [comment]
thx a lot for your response, wish you a happy day^-^

**Comment by woshisuperman** [comment]
> Cesium requires access token of [Cesium ION](https://cesium.com/ion/signin/) to access the WorldTerrain data, and I have removed my expired token in the code, you can register an account to acquire a valid token, and use it according to the [document](https://cesium.com/docs/cesiumjs-ref-doc/Ion.html).
