### ISSUE TITLE
When I zoom in on a wind circle, I don't feel right.

### ISSUE THREAD

**Issue by ZhiqiangCheng** [RaymanNg/3D-Wind-Field#6]
I chose a tornado with a higher wind speed that didn't seem to be the result I wanted. It's okay to have a smaller wind speed.
Like this place：
![图片](https://user-images.githubusercontent.com/25152344/57578932-6b5bc100-74c7-11e9-960c-35ce1237392d.png)
The result is like this：
![图片](https://user-images.githubusercontent.com/25152344/57578951-ab22a880-74c7-11e9-8215-9dcce878db6e.png)

It should actually be like this.
![图片](https://user-images.githubusercontent.com/25152344/57578996-44ea5580-74c8-11e9-9bae-0c38f2618056.png)

I don't know what to do to achieve the desired effect.

**Comment by ZhiqiangCheng** [comment]
When I was showing a visualization of a lake's wind field, I felt sick. I hope somebody can help me.

**Comment by RaymanNg** [comment]
Your issue probably is relative to  'getWind.frag' or 'updatePosition.frag', you may need to modify the GLSL code to make the particles move with the pattern you like.

**Comment by ZhiqiangCheng** [comment]
> Your issue probably is relative to 'getWind.frag' or 'updatePosition.frag', you may need to modify the GLSL code to make the particles move with the pattern you like.

How to Debug GLSL？

**Comment by RaymanNg** [comment]
If you means setting breakpoints in WebGL program, I don't think there is a way to do that.

The only useful tool I found is Spector.JS(already bundled in this repo), which can give a detailed WebGL trace.

**Comment by ZhiqiangCheng** [comment]
I guess Runge-Kutta4 can cause confusion when data is too dense or when data changes dramatically.

**Comment by ZhiqiangCheng** [comment]
> If you means setting breakpoints in WebGL program, I don't think there is a way to do that.
> 
> The only useful tool I found is Spector.JS(already bundled in this repo), which can give a detailed WebGL trace.

thanks, 
I relative to 'getWind.frag'  Runge-Kutta4
vec3 rk4 = (k1 + 2.0 * k2 + 2.0 * k3 + k4) / 6.0;
 -> vec3 rk4 =k1 + (k1 + 2.0 * k2 + 2.0 * k3 + k4) / 6.0;
It has been improved to a certain extent.
![image](https://user-images.githubusercontent.com/25152344/57663008-b3442a80-7624-11e9-9c19-91155264c77f.png)
But when using the data of a lake, it did not achieve the desired results.
![image](https://user-images.githubusercontent.com/25152344/57663110-2e0d4580-7625-11e9-9f91-6142c7e5cc68.png)
The guess is that global accuracy is used.
How to modify it？

**Comment by RaymanNg** [comment]
Sorry for the late reply.

> I guess Runge-Kutta4 can cause confusion when data is too dense or when data changes dramatically.

For this issue, my opinion is RK4 should not be used in this demo, I think the visualization result may be better without RK4, you can have a try.

> But when using the data of a lake, it did not achieve the desired results.

For this issue, if you are using your own custom NetCDF data, I suggest you to check your NetCDF file and make sure it is compatible with this demo, I will update README file later. If you have further question about using custom data, please open a new issue for that and we can discuss there.

**Comment by ZhiqiangCheng** [comment]
> Sorry for the late reply.
> 
> > I guess Runge-Kutta4 can cause confusion when data is too dense or when data changes dramatically.
> 
> For this issue, my opinion is RK4 should not be used in this demo, I think the visualization result may be better without RK4, you can have a try.
> 
> > But when using the data of a lake, it did not achieve the desired results.
> 
> For this issue, if you are using your own custom NetCDF data, I suggest you to check your NetCDF file and make sure it is compatible with this demo, I will update README file later. If you have further question about using custom data, please open a new issue for that and we can discuss there.

I like your 3D-Wind-Field very much, but I know little about GLSL. Thank you very much for your guidance.
