### ISSUE TITLE
Cannot GET data/demo.nc file error

### ISSUE THREAD

**Issue by Jappan07** [RaymanNg/3D-Wind-Field#60]

**Comment by RaymanNg** [comment]
No detail provided, so all I can say is that check your web server configuration if you are running this application locally

**Comment by Jappan07** [comment]
Sorry sir for the incomplete info.
I am running the application locally on my mac and creating an http server using lite-server and it is showing this error in the terminal[
<img width="1080" alt="Screen Shot 2021-03-27 at 4 40 01 PM" src="https://user-images.githubusercontent.com/42716542/112718807-5e111980-8f1b-11eb-8abd-f1d64e3c6f45.png">
](url)

and this in the browser
<img width="1440" alt="Screen Shot 2021-03-27 at 4 41 31 PM" src="https://user-images.githubusercontent.com/42716542/112718817-66695480-8f1b-11eb-859f-bb6a26c2de4a.png">

**Comment by RaymanNg** [comment]
What is the root directory of your lite-server? It should be the path to the cloned repo folder(like the following screenshot). 
![image](https://user-images.githubusercontent.com/18614142/112742720-a257f480-8fc3-11eb-87fc-311de8cf89de.png)

It seems that you are using the subfolder 'Cesium-3D-Wind' as the root directory

**Comment by Jappan07** [comment]
Yes sir you are absolutely correct. I have now used live-server and it is working just fine.
Thank you for your guidance , i ll close the issue now.
