### ISSUE TITLE
can it be used for wave field data,how can i hide the particles with special uv values?

### ISSUE THREAD

**Issue by xiaocui123** [RaymanNg/3D-Wind-Field#61]
I have some hycom data and have converted to netcdf format,but the result show that not only flow fields on the ocean, but also on land,is there anything need to change?
![image](https://user-images.githubusercontent.com/726444/112812284-86ca1800-90af-11eb-9b9b-386b119f17aa.png)
![image](https://user-images.githubusercontent.com/726444/112812863-2ab3c380-90b0-11eb-9e49-82744715db32.png)

thinks for your attention

**Comment by xiaocui123** [comment]
I kown issue #31 can solve my problem,can you give the whole glsl scripts,I am not familiar with it,thanks very much!!

**Comment by RaymanNg** [comment]
No, please learn to write GLSL code yourself.

**Comment by xiaocui123** [comment]
I have resolved this problem thanks a lot.
