### ISSUE TITLE
Some varaible meaning question

### ISSUE THREAD

**Issue by wangzwswip** [RaymanNg/3D-Wind-Field#63]
Dear author, There are  some variaibles I don't understand.
what is meaning about  'lev' , 'U', and 'V'. Thanks a lot!

**Comment by RaymanNg** [comment]
By convention, "lev" means level, which is used as vertical dimension. "U" and "V" are eastward and northward components of wind vector.

Note:
This program does not support rendering multi-levels wind field, so lev dimension should always be 1

**Comment by wangzwswip** [comment]
> By convention, "lev" means level, which is used as vertical dimension. "U" and "V" are eastward and northward components of wind vector.
> 
> Note:
> This program does not support rendering multi-levels wind field, so lev dimension should always be 1

thanks for your
