### ISSUE TITLE
something strange along the longitude 0

### ISSUE THREAD

**Issue by jsbrujy** [RaymanNg/3D-Wind-Field#7]
Hello
Particules have soe issue to be displayed in the zone of longitude 0
here a screen capture on a longitude band with no wind particules

[screen capture link](https://ibb.co/JFkkVwr)

**Comment by RaymanNg** [comment]
Thanks for your report.
It is probably the bug of previous merged PR, you can try the old version repo.
I will take a look at it when I grab more time, maybe two or three days later.

**Comment by jsbrujy** [comment]
My pleasure

 

Hope that will help. I really love your result in Cesium

 

From my side, I use to work with Grib files, especially to extract forecast weather data from the next 12 hours by periods of 1 hours and generating a couple of images to represent the forecasted clouds, temperature, precipitations, wind speed, …

 

I just wonder about your netcdf file : demo.nc. Is it a file you are building by yourself with the U and V information according lev, lat, lon dimensions, or are you downloading an existing file from somewhere?

 

If you are also interested in, I have a process on one of my server producing since 2 years now, forecast data. Especially images with forecasted clouds, temperature, precipitations, ……

Could be nice to make them usable in Wind field?

 

Attached some sample images. This is what is forecasted for today may 13th at 18h UTC.

From what I understood will be nice to have this accessible through a WMS service? Actually I have this accessible on a ftp site

So I could also generate a .nc file per period of 1 hr as well?????

 

Bruno

 



 



 



 

 

De : Rayman <notifications@github.com> 
Envoyé : lundi 13 mai 2019 09:56
À : RaymanNg/3D-Wind-Field <3D-Wind-Field@noreply.github.com>
Cc : bremy <bruno.remy@wanadoo.fr>; Author <author@noreply.github.com>
Objet : Re: [RaymanNg/3D-Wind-Field] something strange along the latitude 0 (#7)

 

Thanks for your report.
It is probably the bug of previous merged PR, you can try the old version repo.
I will take a look at it when I grab more time, maybe two or three days later.

**Comment by RaymanNg** [comment]
> Is it a file you are building by yourself with the U and V information according lev, lat, lon dimensions, or are you downloading an existing file from somewhere?

I downloaded the demo data from [NOAA Global Forecast System website](https://www.ncdc.noaa.gov/data-access/model-data/model-datasets/global-forcast-system-gfs). 
The original data is in GRIB2 format and I used [toolsUI of unidata](https://www.unidata.ucar.edu/software/thredds/v4.5/netcdf-java/ToolsUI.html) to convert the GRIB2 file to a NetCDF V3 file, then I use [NetCDF operators](http://nco.sourceforge.net/) to remove some unneeded data and rename some variables and dimensions to keep it consistent with the NetCDF data in my HPC center.

The reasons why I use NetCDF file in this demo:
- I can not find reliable a JS library that can handle GRIB2(latest standard 2 is preferred) file in browser 
- I found netcdfjs, which is a JS library under active development that can handle NetCDF V3 file (it is a pity that V4 is not supported currently)


> Attached some sample images.

sorry, I can see any images in your post...

> From what I understood will be nice to have this accessible through a WMS service? 

Yes, in fact this demo have used WMS to display several kinds of scalar field data like temperature and precipitations. You can setup your own WMS server and change the URL and WMS parameters in [gui.js](https://github.com/RaymanNg/3D-Wind-Field/blob/master/Cesium-3D-Wind/gui.js) file, ~and I am considering to add some WMS options in GUI to allow more flexibility~(forget it, since WMS has too much URL parameters).


> So I could also generate a .nc file per period of 1 hr as well?????

Of course you can, there are many ways to convert a GRIB file to a NC file. I think GDAL and CDO are some useful tools for that.

**Comment by RaymanNg** [comment]
Close this issue because I have fixed this bug.

Feel free to open a new issue for your new topic.

**Comment by jsbrujy** [comment]
You are the best 

 

De : Rayman <notifications@github.com> 
Envoyé : mardi 14 mai 2019 13:34
À : RaymanNg/3D-Wind-Field <3D-Wind-Field@noreply.github.com>
Cc : bremy <bruno.remy@wanadoo.fr>; Author <author@noreply.github.com>
Objet : Re: [RaymanNg/3D-Wind-Field] something strange along the longitude 0 (#7)

 

Close this issue because I have fixed this bug.

Feel free to open a new issue for your new topic.

**Comment by jsbrujy** [comment]
I am also using the GFS products from NOAA. 

NetCDF and GRIB2 are real complex formats. Not easy to understand and to have something working in a couple of hours!!!!

I will explore how to convert from Grib2 to NetCDF when I will have some free time

 

Here attached a clouds file I am producing from Grib2 data. I’ve made a complex dev in C# with the good libraries to read Grib2 format!!! I had my images integrated in the content of the email but probably they didn’t reach you correctly!!!

 

I am exploring how I can publish my images on a WMS server. But still something I am not familiar at all. So the learning curve is pretty long to do something probably easy when you are aware but difficult when you are starting from scratch!!!

 

So let see when I will have enough time available in front of me to do all of this

 

 

De : Rayman <notifications@github.com> 
Envoyé : mardi 14 mai 2019 12:05
À : RaymanNg/3D-Wind-Field <3D-Wind-Field@noreply.github.com>
Cc : bremy <bruno.remy@wanadoo.fr>; Author <author@noreply.github.com>
Objet : Re: [RaymanNg/3D-Wind-Field] something strange along the longitude 0 (#7)

 

Is it a file you are building by yourself with the U and V information according lev, lat, lon dimensions, or are you downloading an existing file from somewhere?

I downloaded the demo data from NOAA Global Forecast System website <https://www.ncdc.noaa.gov/data-access/model-data/model-datasets/global-forcast-system-gfs> .
The original data is in GRIB2 format and I used toolsUI of unidata <https://www.unidata.ucar.edu/software/thredds/v4.5/netcdf-java/ToolsUI.html>  to convert the GRIB2 file to a NetCDF V3 file, then I use NetCDF operators <http://nco.sourceforge.net/>  to remove some unneeded data and rename some variables and dimensions to keep it consistent with the NetCDF data in my HPC center.

The reasons why I use NetCDF file in this demo:

*	I can not find reliable a JS library that can handle GRIB2(latest standard 2 is preferred) file in browser
*	I found netcdfjs, which is a JS library under active development that can handle NetCDF V3 file (it is a pity that V4 is not supported currently)

Attached some sample images.

sorry, I can see any images in your post...

From what I understood will be nice to have this accessible through a WMS service?

Yes, in fact this demo have used WMS to display several kinds of scalar field data like temperature and precipitations. You can setup your own WMS server and change the URL and WMS parameters in gui.js <https://github.com/RaymanNg/3D-Wind-Field/blob/master/Cesium-3D-Wind/gui.js>  file, and I am considering to add some WMS options in GUI to allow more flexibility.

So I could also generate a .nc file per period of 1 hr as well?????

Of course you can, there are many ways to convert a GRIB file to a NC file. I think GDAL and CDO are some useful tools for that.

**Comment by RaymanNg** [comment]
Again I still can not see the files you attached....

FYI, I think these software can help you:
- [NASA GISS Panoply](https://www.giss.nasa.gov/tools/panoply/), it is a file viewer for both NetCDF and GRIB1/2 files
- [GeoServer](http://geoserver.org/) is can help you setup a WMS server, although there are others tools like MapServer or THREDDS Data Server also can do that, but GeoServer provides a Web UI so that you can configure the server in a easy way.

Good luck.

**Comment by jsbrujy** [comment]
Github is probably deleting file attachments ☹

 

Here a ftp link with my images

ftp://www.dreaminglobe.com:8021/forecastImages.zip

 

Thanks for the tips to be able to produce a .nc file. Will try to make me able to do this

 

Also I identified GeoServer could help to host as a WMS server. Just a little afraid not breaking my servers for the serving web services and other features I have running on it

 

 

 

De : Rayman <notifications@github.com> 
Envoyé : mercredi 15 mai 2019 10:38
À : RaymanNg/3D-Wind-Field <3D-Wind-Field@noreply.github.com>
Cc : bremy <bruno.remy@wanadoo.fr>; Author <author@noreply.github.com>
Objet : Re: [RaymanNg/3D-Wind-Field] something strange along the longitude 0 (#7)

 

Again I still can not see the files you attached....

FYI, I think these software can help you:

*	NASA GISS Panoply <https://www.giss.nasa.gov/tools/panoply/> , it is a file viewer for both NetCDF and GRIB1/2 files
*	GeoServer <http://geoserver.org/>  is can help you setup a WMS server, although there are others tools like MapServer or THREDDS Data Server also can do that, but GeoServer provides a Web UI so that you can configure the server in a easy way.

Good luck.

**Comment by jsbrujy** [comment]
I was able to build a demo2.nc file

I am not using the NetCDF operators since the link if broken to download the windows .exe installation

So I am doing a couple of things in a C# app. I am targeting to be able to construct the .nc file only using a custom app developed in C# 😊

 

Here after a link to load it from my ftp server. Can you tell me if this file is correct?

ftp://www.dreaminglobe.com:8021/demo2.nc

 

On another hand, I was deploying 3D-Wind-Field on my server under IIS

 

When running it, I can see some errors displayed. I can see the Wind setting control panel displayed, the cesium time line control also but no 3D globe. I am testing at the moment with your demo.nc file

 

Here after the errors displayed. What do you think could e wrong in my deployment process??????

 

An error occurred while rendering. Rendering has stopped.

RuntimeError: Fragment shader failed to compile. Compile log: ERROR: 0:? : '' : syntax error t@https://cesiumjs.org/releases/1.57/Build/Cesium/Cesium.js:444:28944 f@https://cesiumjs.org/releases/1.57/Build/Cesium/Cesium.js:468:8851 y@https://cesiumjs.org/releases/1.57/Build/Cesium/Cesium.js:468:11268 d.prototype._bind@https://cesiumjs.org/releases/1.57/Build/Cesium/Cesium.js:468:12283 G@https://cesiumjs.org/releases/1.57/Build/Cesium/Cesium.js:497:13006 z.prototype.draw@https://cesiumjs.org/releases/1.57/Build/Cesium/Cesium.js:497:17231 n.prototype.execute@https://cesiumjs.org/releases/1.57/Build/Cesium/Cesium.js:467:11822 p.prototype.execute@https://cesiumjs.org/releases/1.57/Build/Cesium/Cesium.js:496:15891 i.prototype.execute@https://cesiumjs.org/releases/1.57/Build/Cesium/Cesium.js:488:19128 Ze@https://cesiumjs.org/releases/1.57/Build/Cesium/Cesium.js:522:21612 nt@https://cesiumjs.org/releases/1.57/Build/Cesium/Cesium.js:522:25606 tt@https://cesiumjs.org/releases/1.57/Build/Cesium/Cesium.js:522:22934 mt@https://cesiumjs.org/releases/1.57/Build/Cesium/Cesium.js:523:727 _t@https://cesiumjs.org/releases/1.57/Build/Cesium/Cesium.js:523:914 Me.prototype.render@https://cesiumjs.org/releases/1.57/Build/Cesium/Cesium.js:523:13980 x.prototype.render@https://cesiumjs.org/releases/1.57/Build/Cesium/Cesium.js:530:7492 t@https://cesiumjs.org/releases/1.57/Build/Cesium/Cesium.js:530:952 

 

Thanks

 

 

 

 

 

De : Rayman <notifications@github.com> 
Envoyé : mercredi 15 mai 2019 10:38
À : RaymanNg/3D-Wind-Field <3D-Wind-Field@noreply.github.com>
Cc : bremy <bruno.remy@wanadoo.fr>; Author <author@noreply.github.com>
Objet : Re: [RaymanNg/3D-Wind-Field] something strange along the longitude 0 (#7)

 

Again I still can not see the files you attached....

FYI, I think these software can help you:

*	 <https://www.giss.nasa.gov/tools/panoply/> NASA GISS Panoply, it is a file viewer for both NetCDF and GRIB1/2 files
*	 <http://geoserver.org/> GeoServer is can help you setup a WMS server, although there are others tools like MapServer or THREDDS Data Server also can do that, but GeoServer provides a Web UI so that you can configure the server in a easy way.

Good luck.

**Comment by jsbrujy** [comment]
Here a version 3 for a demo NetCDF file

ftp://www.dreaminglobe.com:8021/demo3.nc

 

if you can validate it is working? Min and max values are correctly setup for U & V

 

This file is produced from a C# app. All is made with line of codes including loading the grib file from NOAA website and building it to NetCDF format

 

Thanks

 

 

 

 

 

De : Rayman <notifications@github.com> 
Envoyé : mercredi 15 mai 2019 10:38
À : RaymanNg/3D-Wind-Field <3D-Wind-Field@noreply.github.com>
Cc : bremy <bruno.remy@wanadoo.fr>; Author <author@noreply.github.com>
Objet : Re: [RaymanNg/3D-Wind-Field] something strange along the longitude 0 (#7)

 

Again I still can not see the files you attached....

FYI, I think these software can help you:

*	NASA GISS Panoply <https://www.giss.nasa.gov/tools/panoply/> , it is a file viewer for both NetCDF and GRIB1/2 files
*	GeoServer <http://geoserver.org/>  is can help you setup a WMS server, although there are others tools like MapServer or THREDDS Data Server also can do that, but GeoServer provides a Web UI so that you can configure the server in a easy way.

Good luck.

**Comment by RaymanNg** [comment]
> What do you think could e wrong in my deployment process??????

The error stack trace does not give me too much information. What I only know is that there is a syntax error in the shader code, maybe file corruption?

> if you can validate it is working?

The data looks good, but Panoply tells me "File type: Hierarchical Data Format, version 5", please keep in mind that the library used in this demo (netcdfjs) only support NetCDF Version 3 file, other file types are not supported, so you need to convert your demo3.nc from HDF5 to NetCDF V3.

**Comment by jsbrujy** [comment]
I deployed by using the “clone or download” green button on the github page

Then using “download zip”

 

I just retried again and I still can see the same error when running my deployed “demo”

 

Do you think the zipfile available on github could contains corrupted data for the shader?

Could you try from your side to use the zipfile content and see if this is working?

 

I just look at the different NetCDF version. The version you are using is called “NetCDF classic”. I think I will be able to generate in that format. I just found a read code in C#. I “just” need to do the “write” code

 

 

De : Rayman <notifications@github.com> 
Envoyé : mardi 21 mai 2019 13:38
À : RaymanNg/3D-Wind-Field <3D-Wind-Field@noreply.github.com>
Cc : bremy <bruno.remy@wanadoo.fr>; Author <author@noreply.github.com>
Objet : Re: [RaymanNg/3D-Wind-Field] something strange along the longitude 0 (#7)

 

What do you think could e wrong in my deployment process??????

The error stack trace does not give me too much information. What I only know is that there is a syntax error in the shader code, maybe file corruption?

if you can validate it is working?

The data looks good, but Panoply tells me "File type: Hierarchical Data Format, version 5", please keep in mind that the library used in this demo (netcdfjs) only support NetCDF Version 3 file, other file types are not supported, so you need to convert your demo3.nc from HDF5 to NetCDF V3.

**Comment by RaymanNg** [comment]
> Could you try from your side to use the zipfile content and see if this is working?

I did try, it works. 
My guess is that you probably have a incorrect server config.  Here are some suggestions:
- Make sure you have added the "data" and "Cesium-3D-Wind/glsl" folders to your IIS serve path
- use "Cesium-3D-Wind/index.html", not "demo/index.html"
- If you still get error, use a debug(unminified) version Cesium library for debug purpose

**Comment by jsbrujy** [comment]
Great let me try this. I was using demo/index.html

 

If was working hard yesterday night on NetCDF “3” format. I am pretty close to populate a correct demo.nc file !

 

 

De : Rayman <notifications@github.com> 
Envoyé : mercredi 22 mai 2019 11:21
À : RaymanNg/3D-Wind-Field <3D-Wind-Field@noreply.github.com>
Cc : bremy <bruno.remy@wanadoo.fr>; Author <author@noreply.github.com>
Objet : Re: [RaymanNg/3D-Wind-Field] something strange along the longitude 0 (#7)

 

Could you try from your side to use the zipfile content and see if this is working?

I did try, it works.
My guess is that you probably have a incorrect server config. Here are some suggestions:

*	Make sure you have added the "data" and "Cesium-3D-Wind/glsl" folders to your IIS serve path
*	use "Cesium-3D-Wind/index.html", not "demo/index.html"
*	If you still get error, use a debug(unminified) version Cesium library for debug purpose

**Comment by jsbrujy** [comment]
Could you tell me if that file now at NetCDF 3 format is working?

ftp://www.dreaminglobe.com:8021/demo5.nc

 

Not yet free time to solve to have the demo working in my IIS. Will try this later

 

 

De : Rayman <notifications@github.com> 
Envoyé : mardi 21 mai 2019 13:38
À : RaymanNg/3D-Wind-Field <3D-Wind-Field@noreply.github.com>
Cc : bremy <bruno.remy@wanadoo.fr>; Author <author@noreply.github.com>
Objet : Re: [RaymanNg/3D-Wind-Field] something strange along the longitude 0 (#7)

 

What do you think could e wrong in my deployment process??????

The error stack trace does not give me too much information. What I only know is that there is a syntax error in the shader code, maybe file corruption?

if you can validate it is working?

The data looks good, but Panoply tells me "File type: Hierarchical Data Format, version 5", please keep in mind that the library used in this demo (netcdfjs) only support NetCDF Version 3 file, other file types are not supported, so you need to convert your demo3.nc from HDF5 to NetCDF V3.

**Comment by jsbrujy** [comment]
I am able to run the demo on my IIS now. The issue was to make extensions .vert and .frag accessible through HTTP requests in IIS !

 

So my new NetCDF format is readable by your developpement. However I am not sure my U and V data are correctly injected in the NetCDF file

 

Can you tell me for U and V data with that following dimensions [lev, time, lat, lon] if the first data for [0, 0, 0, 0] corresponds to:

*	Lon 0, lat 90, or 
*	Lon 0, lat -90 or
*	Lon -180, lat 90 or
*	Lon -180, lat -90 

 

 

De : Rayman <notifications@github.com> 
Envoyé : mercredi 22 mai 2019 11:21
À : RaymanNg/3D-Wind-Field <3D-Wind-Field@noreply.github.com>
Cc : bremy <bruno.remy@wanadoo.fr>; Author <author@noreply.github.com>
Objet : Re: [RaymanNg/3D-Wind-Field] something strange along the longitude 0 (#7)

 

Could you try from your side to use the zipfile content and see if this is working?

I did try, it works.
My guess is that you probably have a incorrect server config. Here are some suggestions:

*	Make sure you have added the "data" and "Cesium-3D-Wind/glsl" folders to your IIS serve path
*	use "Cesium-3D-Wind/index.html", not "demo/index.html"
*	If you still get error, use a debug(unminified) version Cesium library for debug purpose

**Comment by RaymanNg** [comment]
You should use tools like Panoply or others, they can give you answer immediately, no need to ask me every time....

For you question, array[0] is the data at (lon 0, lat -90), this screenshot of Panoply should help you understand the data layout
![image](https://user-images.githubusercontent.com/18614142/58364512-26cd1e00-7ee8-11e9-8c94-1425221ec8b2.png)

Note: my demo lon data is from[0, 360], NOT [-180, 180]

**Comment by jsbrujy** [comment]
Thank you. I was not discovering this feature in Panoply. This is really useful

So now my data are well generated

 

This is coherent when comparing what’s is displayed with your solution and nullschool for data at the same date/hr

 

 



 



 

De : Rayman <notifications@github.com> 
Envoyé : samedi 25 mai 2019 06:26
À : RaymanNg/3D-Wind-Field <3D-Wind-Field@noreply.github.com>
Cc : bremy <bruno.remy@wanadoo.fr>; Author <author@noreply.github.com>
Objet : Re: [RaymanNg/3D-Wind-Field] something strange along the longitude 0 (#7)

 

You should use tools like Panoply or others, they can give you answer immediately, no need to ask me every time....

For you question, array[0] is the data at (lon 0, lat -90), this screenshot of Panoply should help you understand the data layout
 <https://user-images.githubusercontent.com/18614142/58364512-26cd1e00-7ee8-11e9-8c94-1425221ec8b2.png>

**Comment by jsbrujy** [comment]
Here the imagery I am able to generate for Wind speed to be close to the NullSchool rendering

 

 



 

 

 

 

De : Rayman <notifications@github.com> 
Envoyé : samedi 25 mai 2019 06:26
À : RaymanNg/3D-Wind-Field <3D-Wind-Field@noreply.github.com>
Cc : bremy <bruno.remy@wanadoo.fr>; Author <author@noreply.github.com>
Objet : Re: [RaymanNg/3D-Wind-Field] something strange along the longitude 0 (#7)

 

You should use tools like Panoply or others, they can give you answer immediately, no need to ask me every time....

For you question, array[0] is the data at (lon 0, lat -90), this screenshot of Panoply should help you understand the data layout
 <https://user-images.githubusercontent.com/18614142/58364512-26cd1e00-7ee8-11e9-8c94-1425221ec8b2.png>
