### ISSUE TITLE
how to produce demo.nc?

### ISSUE THREAD

**Issue by martin416** [RaymanNg/3D-Wind-Field#9]
Can you tell me,how to product demo.nc data file please?
I found some history:
Wed Apr 17 10:29:08 2019: D:\\GreenSoft\\Science\\Data_Processing_Analysis_Visualization\\NetCDF_Operators\\ncap2.exe -3 -S getMinMax.nco C:\\Users\\Rayman\\Downloads\\tempInvDim.nc C:\\Users\\Rayman\\Downloads\\uv.nc
Wed Apr 17 10:29:07 2019: D:\\GreenSoft\\Science\\Data_Processing_Analysis_Visualization\\NetCDF_Operators\\ncpdq.exe -a -lat C:\\Users\\Rayman\\Downloads\\tempFixDim.nc C:\\Users\\Rayman\\Downloads\\tempInvDim.nc
Wed Apr 17 10:29:07 2019: D:\\GreenSoft\\Science\\Data_Processing_Analysis_Visualization\\NetCDF_Operators\\ncks.exe --no_rec_dmn lev C:\\Users\\Rayman\\Downloads\\tempRecDim.nc C:\\Users\\Rayman\\Downloads\\tempFixDim.nc
Wed Apr 17 10:29:07 2019: D:\\GreenSoft\\Science\\Data_Processing_Analysis_Visualization\\NetCDF_Operators\\ncecat.exe -u lev C:\\Users\\Rayman\\Downloads\\tempLevDim.nc C:\\Users\\Rayman\\Downloads\\tempRecDim.nc
Wed Apr 17 10:29:07 2019: D:\\GreenSoft\\Science\\Data_Processing_Analysis_Visualization\\NetCDF_Operators\\ncap2.exe -S defineLev.nco C:\\Users\\Rayman\\Downloads\\tempUV.nc C:\\Users\\Rayman\\Downloads\\tempLevDim.nc
Wed Apr 17 10:29:07 2019: D:\\GreenSoft\\Science\\Data_Processing_Analysis_Visualization\\NetCDF_Operators\\ncrename.exe -v u-component_of_wind_planetary_boundary,U -v v-component_of_wind_planetary_boundary,V C:\\Users\\Rayman\\Downloads\\tempWind.nc C:\\Users\\Rayman\\Downloads\\tempUV.nc
Wed Apr 17 10:29:06 2019: D:\\GreenSoft\\Science\\Data_Processing_Analysis_Visualization\\NetCDF_Operators\\ncks.exe -v u-component_of_wind_planetary_boundary,v-component_of_wind_planetary_boundary C:\\Users\\Rayman\\Downloads\\20180916.nc C:\\Users\\Rayman\\Downloads\\tempWind.nc
Read using CDM IOSP GribCollection v3

but I dont have some data,like tempInvDim.nc,uv.nc ...
Can you upload these files?THANKS!

**Comment by RaymanNg** [comment]
Actually the data is from [NOAA GFS](https://www.ncdc.noaa.gov/data-access/model-data/model-datasets/global-forcast-system-gfs), I just converted it from GRIB2 to NetCDF 3 format, and then used NetCDF operators to extract and process the data I need.

I don't think you should need the tempInvDim.nc or uv.nc if you want to use custom NetCDF data. Just make your own and ensure it contains the necessary values in the required format (read the updated README file for more info)

**Comment by 1287642889** [comment]
hello,can you tell me where are the NetCDF data from and how can i get it? thank you!

**Comment by RaymanNg** [comment]
The demo data is downloaded from [NOAA Global Forecast System](https://www.ncdc.noaa.gov/data-access/model-data/model-datasets/global-forcast-system-gfs).
The original data is in GRIB2 format and I used [toolsUI](https://www.unidata.ucar.edu/software/thredds/v4.5/netcdf-java/ToolsUI.html) to convert the GRIB2 file to a NetCDF V3 file

**Comment by 1287642889** [comment]
hello, the demo only shows the wind direction，how does the demo to show the wind power？thank you!

**Comment by 1287642889** [comment]
could you tell me how to download and show other climate data? for example ocean data、temperature data、humidity data and so on，thank you!

**Comment by RaymanNg** [comment]
Wind power is displayed by color

The scalar field (one value at one position, for example, temperature and humidity) can be displayed by WMS layer, you can read the source code in wind3D.js and the document of Cesium for how to use WMS layer

**Comment by xqwIOS** [comment]
Excuse me， I use new netcdfjs(file) This file is provided by you named demo.nc but I got an  ERROR that is  'Not a valid NetCDF v3.x file:  should start with CDF' and I print the buffer.readByt(3) return "<!D" 
![屏幕快照 2019-07-05 下午3 58 58](https://user-images.githubusercontent.com/25758061/60707221-d52f9e80-9f3d-11e9-9b80-9d89476720e0.png)
can you tell me how to resolve this problem  Thanks

**Comment by RaymanNg** [comment]
Do you mean you use a different version netcdfjs library? If so, please make sure you are using the latest version.

If you did not change the netcdfjs library, please check your netcdf file version, the README file states clearly that you should use netcdf v3 file

**Comment by xqwIOS** [comment]
Thanks can you tell me that whitch Version about Cessium you used. now I Got An Error:[Cesium WebGL] Fragment shader compile log: ERROR: 0:? : '' : syntax error and my cessum version is 1.59.0

**Comment by RaymanNg** [comment]
@xqwIOS 
Sorry, I am busy these days...

For your problem, I think you should check your GLSL files location, because "ERROR: 0:? : '' indicates you are probably reading an non-exist file

**Comment by xqwIOS** [comment]
OK ， Thanks
